### ISSUE TITLE
Reverse option for asymmetric diverging colors not respecting left and right

### ISSUE THREAD

**Issue by joewdavies** [riatelab/dicopal.js#11]
Hi again!

I've been testing the latest release in our app and it works like a charm! our [custom palettes](https://observablehq.com/@joewdavies/eurostat-color-palettes) are fully integrated with Dicopal :)

I noticed a minor issue when reversing unbalanced diverging schemes:

If you reverse, the left and right parameters are not reflected in the colors returned.

![image](https://github.com/riatelab/dicopal.js/assets/25485293/40d37e10-d7f8-42fb-bc8d-792472037f2e)

I suppose that the expected behavior in this example would be that there are 4 reds to the left and 2 blues to the right.

Screenshot taken from this notebook: https://observablehq.com/d/7a162d4ac1f308bb

Thanks again for your marvelous work!

Joe

**Comment by mthh** [comment]
Thank you for your feedback and your kind words!

You're right, I guess currently it simply inverts the generated palette rather than inverting the number of classes left and right before generating it :facepalm::sweat_smile:

I'm going to fix this soon (we're facing this issue in one of our app too).
